language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
env:
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=py38
    - TOXENV=pep8
    - TOXENV=coverage
matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.8"
          env: TOXENV=pep8
        - python: "3.8"
          env: TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
deploy:
    provider: pypi
    user: seantis
    password:
        secure: IMa00gAAWaRAPhaLe0UqonbaW9dT7vyKTvpjrIGrlb3TkFmej2BoKxRjgMHvfWUQA2pR/2iDOgQF5o203Aox2ByAeBge0dVwRRWyaTkgIBJGL3yHDobhVUlHjjyLgP5o4K5V3frMOuNgaNelh+mzyPC6Vd3XmrN/F4HT70/GoN0=
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        condition: $TOXENV = py37
